name: Solo en Main

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Workflow ejecutado solo en la rama main"
